server:
  port: 8014
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.antares.chatdev.controller
knife4j:
  enable: true
  setting:
    language: zh_cn